server:
  port: 8080

spring:
  application:
    name: excel-reconciler
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

gemini:
  api:
    key: ${GEMINI_API_KEY:AIzaSyD6HUbhja1YzZC-JIUnQtXqQMx8qreIpS8}
    model: ${GEMINI_API_MODEL:gemini-flash-latest}
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models}

