server:
  port: 8080

spring:
  application:
    name: excel-reconciler
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

ollama:
  api:
    model: ${OLLAMA_API_MODEL:qwen3-vl:8b-instruct}
    url: ${OLLAMA_API_URL:http://localhost:11434/api/chat}
